print("Hello AI World")
print("This is my first project using AI")
print("I am learning how to use AI to create projects")
print("I am excited to see what I can create with AI")
print("I am going to keep learning and improving my skills")
print("I am going to create amazing projects with AI")
print("I am going to share my projects with the world")
print("I am going to inspire others to learn AI")
print("I am going to have fun while learning AI")
print("I am going to make a positive impact with AI")